using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using CRMS_Peguit.domain.Common;
using CRMS_Peguit.winforms.Auth;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CRMS_Peguit.winforms.Services
{
    public class ReportsApiService : BaseApiService
    {
        public ReportsApiService(string? baseUrl = null, HttpClient? httpClient = null)
            : base(baseUrl, httpClient)
        {
            QuestPDF.Settings.License = LicenseType.Community;
        }

        public List<SalesReportRow> GetSalesReport(DateRangeFilter range, int? agentId = null, string? propertyType = null)
        {
            var uri = "api/reports/sales?";
            if (agentId.HasValue) uri += $"agentId={agentId.Value}&";
            if (!string.IsNullOrWhiteSpace(propertyType)) uri += $"propertyType={Uri.EscapeDataString(propertyType)}&";

            return Post<DateRangeFilter, List<SalesReportRow>>(uri.TrimEnd('&', '?'), range) ?? new();
        }

        public List<LeadProgressRow> GetLeadProgressReport(DateRangeFilter range, int? agentId = null, string? source = null)
        {
            var uri = "api/reports/lead-progress?";
            if (agentId.HasValue) uri += $"agentId={agentId.Value}&";
            if (!string.IsNullOrWhiteSpace(source)) uri += $"source={Uri.EscapeDataString(source)}&";

            return Post<DateRangeFilter, List<LeadProgressRow>>(uri.TrimEnd('&', '?'), range) ?? new();
        }

        public List<CommissionReportRow> GetCommissionReport(DateRangeFilter range, int? agentId = null)
        {
            var uri = "api/reports/commissions?";
            if (agentId.HasValue) uri += $"agentId={agentId.Value}&";

            return Post<DateRangeFilter, List<CommissionReportRow>>(uri.TrimEnd('&', '?'), range) ?? new();
        }

        public List<PropertyInventoryReportRow> GetPropertyInventoryReport(DateRangeFilter range, string? propertyType = null, string? status = null)
        {
            var uri = "api/reports/inventory?";
            if (!string.IsNullOrWhiteSpace(propertyType)) uri += $"propertyType={Uri.EscapeDataString(propertyType)}&";
            if (!string.IsNullOrWhiteSpace(status)) uri += $"status={Uri.EscapeDataString(status)}&";

            return Post<DateRangeFilter, List<PropertyInventoryReportRow>>(uri.TrimEnd('&', '?'), range) ?? new();
        }

        public List<TicketResolutionRow> GetTicketResolutionReport(DateRangeFilter range, string? priority = null, string? status = null)
        {
            var uri = "api/reports/tickets?";
            if (!string.IsNullOrWhiteSpace(priority)) uri += $"priority={Uri.EscapeDataString(priority)}&";
            if (!string.IsNullOrWhiteSpace(status)) uri += $"status={Uri.EscapeDataString(status)}&";

            return Post<DateRangeFilter, List<TicketResolutionRow>>(uri.TrimEnd('&', '?'), range) ?? new();
        }

        public List<AgentActivityRow> GetAgentActivityReport(DateRangeFilter range, int? agentId = null)
        {
            var uri = "api/reports/agent-activity?";
            if (agentId.HasValue) uri += $"agentId={agentId.Value}&";

            return Post<DateRangeFilter, List<AgentActivityRow>>(uri.TrimEnd('&', '?'), range) ?? new();
        }

        public List<AgentPickerItem> GetAgentList() =>
            Get<List<AgentPickerItem>>("api/reports/agents") ?? new();

        public void ExportToCsv<T>(List<T> data, string filePath, ReportHeader header)
        {
            if (typeof(T) == typeof(CommissionReportRow) && !RbacService.CanExportFinancialSettlements)
                throw new UnauthorizedAccessException("Commission and financial settlement exports are restricted to Administrators.");

            try
            {
                using var writer = new StreamWriter(filePath, false, Encoding.UTF8);
                writer.WriteLine($"# NEXA CRM — Executive Report");
                writer.WriteLine($"# Report Name: {header.ReportName}");
                writer.WriteLine($"# Date Range: {header.DateRange}");
                writer.WriteLine($"# Generated By: {header.GeneratedBy}");
                writer.WriteLine($"# Generated At: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
                writer.WriteLine();

                PropertyInfo[] props = GetReportDisplayProperties<T>();
                var headerLine = string.Join(",", props.Select(p => EscapeCsv(FormatHeaderName(p.Name))));
                writer.WriteLine(headerLine);

                foreach (var item in data)
                {
                    var values = props.Select(p =>
                    {
                        var val = p.GetValue(item, null);
                        return EscapeCsv(FormatCellValue(p, val));
                    });
                    writer.WriteLine(string.Join(",", values));
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Error in ExportToCsv: {ex.Message}");
            }
        }

        private static string EscapeCsv(string value)
        {
            if (string.IsNullOrEmpty(value)) return "";
            if (value.Contains(",") || value.Contains("\"") || value.Contains("\n") || value.Contains("\r"))
            {
                return $"\"{value.Replace("\"", "\"\"")}\"";
            }
            return value;
        }

        public void ExportToPdf<T>(List<T> data, string filePath, ReportHeader header)
        {
            if (typeof(T) == typeof(CommissionReportRow) && !RbacService.CanExportFinancialSettlements)
                throw new UnauthorizedAccessException("Commission and financial settlement exports are restricted to Administrators.");

            try
            {
                PropertyInfo[] props = GetReportDisplayProperties<T>();

                Document.Create(container =>
                {
                    container.Page(page =>
                    {
                        page.Margin(30);
                        page.Size(PageSizes.A4.Landscape());
                        page.PageColor(Colors.White);
                        page.DefaultTextStyle(x => x.FontSize(9).FontFamily("Arial"));

                        page.Header().Column(col =>
                        {
                            col.Item().Row(r =>
                            {
                                r.RelativeItem().Column(c =>
                                {
                                    c.Item().Text("NEXA REAL ESTATE CRM").Bold().FontSize(18).FontColor(Colors.Blue.Darken2);
                                    c.Item().Text(header.ReportName).Bold().FontSize(13).FontColor(Colors.Grey.Darken3);
                                });
                                r.RelativeItem().AlignRight().Column(c =>
                                {
                                    c.Item().Text($"Generated: {header.GeneratedAt:yyyy-MM-dd HH:mm}").FontSize(8).FontColor(Colors.Grey.Darken1);
                                    c.Item().Text($"By: {header.GeneratedBy}").FontSize(8).FontColor(Colors.Grey.Darken1);
                                    c.Item().Text($"Period: {header.DateRange}").FontSize(8).FontColor(Colors.Grey.Darken1);
                                });
                            });
                            col.Item().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Blue.Darken2);
                        });

                        page.Content().PaddingVertical(10).Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                foreach (var p in props)
                                {
                                    if (p.Name.Contains("Address") || p.Name.Contains("Customer") || p.Name.Contains("LeadName"))
                                        columns.RelativeColumn(3);
                                    else if (p.Name.Contains("Ref") || p.Name.Contains("Agent") || p.Name.Contains("Status") || p.Name.Contains("Stage"))
                                        columns.RelativeColumn(2);
                                    else
                                        columns.RelativeColumn(1.8f);
                                }
                            });

                            table.Header(h =>
                            {
                                foreach (var p in props)
                                {
                                    h.Cell().Background(Colors.Grey.Lighten3).Padding(4)
                                        .Text(FormatHeaderName(p.Name)).Bold().FontSize(8).FontColor(Colors.Grey.Darken3);
                                }
                            });

                            foreach (var item in data)
                            {
                                foreach (var p in props)
                                {
                                    var val = p.GetValue(item, null);
                                    string cellText = FormatCellValue(p, val);
                                    bool isNumeric = p.PropertyType == typeof(decimal) || p.PropertyType == typeof(double) || p.PropertyType == typeof(int);

                                    var cell = table.Cell().BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(4);
                                    if (isNumeric)
                                    {
                                        cell.AlignRight().Text(cellText).FontSize(8);
                                    }
                                    else
                                    {
                                        cell.AlignLeft().Text(cellText).FontSize(8);
                                    }
                                }
                            }
                        });

                        page.Footer().Column(f =>
                        {
                            f.Item().LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
                            f.Item().PaddingTop(4).Row(r =>
                            {
                                r.RelativeItem().Text("CONFIDENTIAL · Real Estate Business Intelligence").FontSize(8).FontColor(Colors.Grey.Darken1);
                                r.RelativeItem().AlignRight().Text(x =>
                                {
                                    x.DefaultTextStyle(t => t.FontSize(8).FontColor(Colors.Grey.Darken1));
                                    x.Span("Page ");
                                    x.CurrentPageNumber();
                                    x.Span(" of ");
                                    x.TotalPages();
                                });
                            });
                        });
                    });
                })
                .GeneratePdf(filePath);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Error in ExportToPdf: {ex.Message}");
            }
        }

        private static PropertyInfo[] GetReportDisplayProperties<T>()
        {
            var ignoredAliases = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "Value", "ClosedDate", "DaysInStage", "CommissionRate", "CommissionAmount", "LeadsWorked"
            };

            if (!RbacService.CanViewBrokerageMargins)
            {
                ignoredAliases.Add("BrokerageRetainedAmount");
            }

            return typeof(T).GetProperties()
                .Where(p => !ignoredAliases.Contains(p.Name))
                .ToArray();
        }

        private static string FormatHeaderName(string propName)
        {
            return propName switch
            {
                "DealRef" => "Deal Ref",
                "CustomerName" => "Customer Name",
                "PropertyAddress" => "Property Address",
                "PropertyType" => "Property Type",
                "AgentName" => "Assigned Agent",
                "DealValue" => "Deal Value (₱)",
                "Commission" => "Commission (₱)",
                "GrossCommission" => "Gross Comm (₱)",
                "AgentSplitPercent" => "Agent Split %",
                "AgentPayoutAmount" => "Agent Payout (₱)",
                "BrokerageRetainedAmount" => "Brokerage Net (₱)",
                "SettlementStatus" => "Settlement Status",
                "ExpectedOrClosedDate" => "Closing / Expected Date",
                "PropertyRef" => "Property Ref",
                "ListingPrice" => "Listing Price (₱)",
                "ListingAgent" => "Listing Agent",
                "DaysOnMarket" => "Days on Market",
                "AssociatedDeals" => "Active Deals",
                "ListedDate" => "Listed Date",
                "LeadName" => "Lead Name",
                "EstimatedBudget" => "Est. Budget (₱)",
                "DaysInPipeline" => "Days in Pipeline",
                "ConvertedToCustomer" => "Converted",
                "CreatedDate" => "Created Date",
                "TicketNumber" => "Ticket #",
                "OpenedDate" => "Opened Date",
                "ResolvedDate" => "Resolved Date",
                "ResolutionTime" => "Resolution Time",
                "SlaMet" => "SLA Met",
                "ActiveLeads" => "Active Leads",
                "LeadsConverted" => "Converted Leads",
                "ConversionRate" => "Conv. Rate %",
                "DealsClosed" => "Deals Closed",
                "TotalSalesVolume" => "Sales Volume (₱)",
                "TotalCommissionEarned" => "Commission Earned (₱)",
                "FollowUpsCompleted" => "Follow-Ups Done",
                "TicketsResolved" => "Tickets Resolved",
                _ => Regex.Replace(propName, "([A-Z])", " $1").Trim()
            };
        }

        private static string FormatCellValue(PropertyInfo prop, object? val)
        {
            if (val == null) return "-";
            if (val is decimal dec)
            {
                if (prop.Name.Contains("Percent") || prop.Name.Contains("Rate"))
                    return $"{dec:F1}%";
                return dec.ToString("N2", CultureInfo.InvariantCulture);
            }
            if (val is double dbl)
            {
                if (prop.Name.Contains("Rate") || prop.Name.Contains("Percent"))
                    return $"{dbl:F1}%";
                return dbl.ToString("N1", CultureInfo.InvariantCulture);
            }
            if (val is int num)
            {
                return num.ToString("N0", CultureInfo.InvariantCulture);
            }
            return val.ToString() ?? "-";
        }
    }
}
